[tool.poetry]
name = "tex_table_compiler"
version = "0.1.0"
description = ""
authors = ["janfasnacht <jan.fasnacht@gmail.com>"]
readme = "README.md"
packages = [
    { include = "tex_compiler" }
]

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
pymupdf = "^1.24.11"
numpy = "^2.1.2"
pillow = "^10.4.0"
flask = "^3.1.0"
flask-cors = "^5.0.0"
pytest = "^8.3.4"
flask-swagger-ui = "^4.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
