[tool.poetry]
name = "utils"
version = "0.1.0"
description = ""
authors = ["janfasnacht <jan.fasnacht@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.7"
pymupdf = "^1.24.11"
numpy = "^2.1.2"
pillow = "^10.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
